CREATE TABLE CLIENTE(
    ID_CLIENTE NUMBER(10) PRIMARY KEY, 
    NOME VARCHAR2(120) NOT NULL,
    DATA_NASC DATE NOT NULL,
    GENERO CHAR(1) NOT NULL,
    CPF CHAR(14) NULL,
    CONSTRAINT CK_GENERO_CLI CHECK (GENERO IN('M', 'F')),
    CONSTRAINT UQ_CLI_CPF UNIQUE (CPF)
);

CREATE TABLE VEICULO (
    PLACA VARCHAR(7) PRIMARY KEY,
    MODELO VARCHAR(50),
    MARCA VARCHAR(50),
    ANO INT,
    COR VARCHAR(20),
    CLIENTE_CPF VARCHAR(11),
    CONSTRAINT FK_CLIENTE FOREIGN KEY (CLIENTE_CPF) REFERENCES CLIENTE(CPF)
);

CREATE TABLE OFICINA (
    CNPJ VARCHAR(14) PRIMARY KEY,
    NOME_FANTASIA VARCHAR(100),
    ENDERECO VARCHAR(200)
);

CREATE TABLE ORDEM_DE_SERVICO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO TEXT,
    DATA_ENTRADA DATE,
    DATA_SAIDA DATE,
    VALOR DECIMAL(10, 2),
    STATUS VARCHAR(50),
    OFICINA_CNPJ VARCHAR(14),
    CONSTRAINT FK_OFICINA FOREIGN KEY (OFICINA_CNPJ) REFERENCES OFICINA(CNPJ)
);